// Gym_fin/react-front/src/app/exercises/page.tsx
"use client"

import { ExerciseCategoryService } from "@/services/ExerciseCategoryService"
import {useContext, useEffect, useState} from "react";
import {AccountContext} from "@/context/AccountContext";
import {useRouter} from "next/navigation";
import {IExercise} from "@/types/domain/IExercise";
import {set} from "react-hook-form";
import Link from "next/link";
import {IExerciseCategory} from "@/types/domain/IExerciseCategory";
export default function Exercises() {
    const exerciseService = new ExerciseCategoryService();
    const { accountInfo } = useContext(AccountContext);
    const router =useRouter();
    const [data, setData] = useState<IExerciseCategory[]>([]);
    const [searchQuery, setSearchQuery] = useState("");


    useEffect(() => {
        if (!accountInfo?.jwt) {
            router.push("/login");
        }
        const fetchData = async () => {
            try {
                const result = await exerciseService.getAllAsync();
                if (result.errors) {
                    console.log(result.errors);
                    return;
                }
                setData(result.data!);
            } catch (error) {
                console.error("Error fetching data:", error);
            }
        };
        fetchData();
    }, []);
    if (data.length === 0) {
        return "Loading..."
    }
    // Filter based on search query
    const filteredData = Object.entries(data).filter(([category, exercises]) =>
        exercises.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        exercises.exercises?.some(ex =>
            ex.name.toLowerCase().includes(searchQuery.toLowerCase())
        )
    );

    return (
        <>
            <div className="container mt-5">
                <h1>All Exercises</h1>

                <Link href="/makeExercise">
                    <button type="button" className="btn btn-success mb-4">Add New Exercise</button>
                </Link>
                <div className="mb-4">
                    <input
                        type="text"
                        className="form-control"
                        placeholder="Search by category or exercise name"
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                    />
                </div>
                {data.length === 0 ? (
                    <div>No Exercises found.</div>
                ) : (
                    // Flatten and filter all exercises across all categories
                    data
                        .flatMap((category) => category.exercises?.map((ex) => ({
                            ...ex,
                            categoryName: category.name // Optional: retain category name for display
                        })))
                        .filter((exercise) =>
                            exercise?.name.toLowerCase().includes(searchQuery.toLowerCase())
                        )
                        .map((exercise) => (
                            <div key={exercise!.id} className="col-md-4 mb-4 exercise-card">
                                <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">{exercise!.name}</h5>
                                        <p className="card-text">
                                            {exercise!.desc || "No description provided"}
                                        </p>
                                        <p className="text-muted"><small>{exercise!.categoryName}</small></p>
                                        <button className="btn btn-danger">Delete Exercise</button>
                                    </div>
                                </div>
                            </div>
                        ))
                )}
            </div>
        </>
    )};

// Gym_fin/Frontend(Vue)/src/views/Exercise/Exercises.vue
<script setup lang="ts">
import { onMounted, reactive, ref, computed } from 'vue'
import { ExerciseCategoryService } from '@/services/ExerciseCategoryService.ts'
import type { IResultObject } from '@/types.ts'
import type { IExerciseCategory } from '@/domain/IExerciseCategory.ts'
import { RouterLink } from 'vue-router'

const requestIsOngoing = ref(false)
const data = reactive<IResultObject<IExerciseCategory[]>>({})
const searchQuery = ref('')

const fetchPageData = async () => {
  requestIsOngoing.value = true
  try {
    const service = new ExerciseCategoryService()
    const result = await service.getAllAsync()

    data.data = result.data
    data.errors = result.errors

    requestIsOngoing.value = false
  } catch (error) {
    console.error(error)
  } finally {
    requestIsOngoing.value = false
  }
}
onMounted(async () => {
  await fetchPageData()
})

const filteredData = computed(() => {
  const q = searchQuery.value.toLowerCase().trim()
  if (!q) {
    return data.data
  }

  return data.data!
    .map((cat) => {
      const filteredExercises = cat.exercises?.filter(
        (ex) => cat.name.toLowerCase().includes(q) || ex.name.toLowerCase().includes(q),
      )
      return filteredExercises && filteredExercises.length > 0
        ? { ...cat, exercises: filteredExercises }
        : null
    })
    .filter(Boolean)
})
</script>

<template>
  <div class="container mt-5">
    <h1>All Exercises</h1>

    <router-link to="/makeExercise">
      <button type="button" class="btn btn-success mb-4">Add New Exercise</button>
    </router-link>
    <div class="mb-4">
      <input
        v-model="searchQuery"
        type="text"
        class="form-control"
        placeholder="Search by category or exercise name"
      />
    </div>
    <div v-if="data.data">
      <div v-for="category in filteredData" :key="category!.name" class="category">
        <h2 class="category-title">{{ category!.name }}</h2>
        <div class="row">
          <div
            v-for="exercise in category!.exercises"
            :key="exercise.name"
            class="col-md-4 exercise-card"
          >
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ exercise.name }}</h5>
                <p class="card-text">
                  {{ exercise.desc || 'No description provided' }}
                </p>
                <button class="btn btn-danger">Delete Exercise</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    <div v-else>
      No Exercises found.
    </div>
  </div>
</template>

<style scoped>
.category-title {
  margin-top: 30px;
  border-bottom: 2px solid #ccc;
  padding-bottom: 5px;
}

.card {
  margin-bottom: 20px;
  transition:
    transform 0.3s ease,
    box-shadow 0.3s ease;
}

.card:hover {
  transform: scale(1.05);
  box-shadow: 0 8px rgba(0, 0, 0, 0.2);
}

.btn-outline-light {
  margin-left: 10px;
}
</style>

<style scoped></style>
