// Gym_fin/Frontend(Vue)/src/nav/Header.vue
<script setup lang="ts">
import { RouterLink, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth.ts';
import { computed, ref } from 'vue'
import AccountService from '@/services/AccountService.ts'

const userStore = useAuthStore();
const router = useRouter();
const authStore = useAuthStore();



let loginIsOngoing = ref(false);
let errors = ref<string[]>([]);

const doLogout = async () => {
  const refreshToken = authStore.refreshToken;
  const jwt = authStore.jwt;
  loginIsOngoing.value = true;
  const res = await AccountService.logoutAsync(jwt!, refreshToken!);

  if (res.data) {
    authStore.clearTokens();
    errors.value = [];
    await router.push('/');
  } else {
    errors.value = res.errors!;
  }

  loginIsOngoing.value = false;
}

const isLoggedIn = computed(() => userStore.isAuthenticated)

</script>


<template>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" href="/">WebApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul v-if="isLoggedIn" class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/workouts">Workouts</RouterLink>
            </li>

            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/exercises">Exercises</RouterLink>
            </li>
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/statistics">Statistics</RouterLink>
            </li>
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/shareWorkout">Search for workouts</RouterLink>
            </li>

          </ul>

          <ul v-if="!isLoggedIn" class="navbar-nav">
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/register">Register</RouterLink>
            </li>
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" to="/login">Login</RouterLink>
            </li>
          </ul>

          <ul v-else class="navbar-nav">
            <li class="nav-item">
              <RouterLink class="nav-link text-dark" @click="doLogout()" to="/login">Logout</RouterLink>
            </li>
          </ul>

        </div>
      </div>
    </nav>
  </header>
</template>

// Gym_fin/react-front/src/components/Header.tsx
"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useContext } from "react";
import {AccountContext} from "@/context/AccountContext";
import {SubmitHandler} from "react-hook-form";
import {AccountService} from "@/services/AccountService";

export default function Header() {
    const { accountInfo, setAccountInfo } = useContext(AccountContext);
    const router = useRouter();
    const accountService = new AccountService();
    type Inputs = {
        jwt: string;
        refreshToken: string;
    }

    const onClick  = async (jwt: string | undefined, refreshToken: string | undefined) => {
        try {
            const result = await accountService.logoutAsync(jwt!, refreshToken!);
            console.log(result);
            if (result.errors) {
                console.log(result.errors);
                return;
            }
        } catch (err) {
            console.error(err);
        }
    };

    return (
        <>
            <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div className="container">
                    <Link className="navbar-brand" href="/">GymApp</Link>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link className="nav-link text-dark" href="/">Home</Link>
                            </li>

                            {accountInfo?.jwt &&
                                <li className="nav-item dropdown">
                                    <a className="nav-link text-dark dropdown-toggle" href="javascript:{}" id="userDropdown"
                                       role="button" data-bs-toggle="dropdown" aria-expanded="false">User</a>
                                    <div className="dropdown-menu" aria-labelledby="userDropdown">
                                        <Link className="dropdown-item text-dark" href="/exercises">Exercises</Link>
                                    </div>
                                </li>
                            }

                        </ul>
                        <ul className="navbar-nav">
                            <li className="nav-item">
                        {accountInfo?.jwt &&
                                    <a className="nav-link text-dark" href="#" onClick={() => {
                                        setAccountInfo!({});
                                        onClick(accountInfo?.jwt, accountInfo?.refreshToken).then(r =>
                                        router.push("/login"));
                                    }}>Logout</a>
                        }
                        {!accountInfo?.jwt &&
                        <Link className="dropdown-item text-dark" href="/login">Login</Link>
                        }
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>


        </>
    );
}
