// Gym_fin/react-front/src/app/login/page.tsx
"use client"
import { SubmitHandler, useForm} from "react-hook-form";
import { useContext, useState } from "react";
import { AccountService } from "@/services/AccountService";
import { AccountContext } from "@/context/AccountContext";
import { useRouter } from "next/navigation";


export default function Login() {
    const accountService = new AccountService();
    const { setAccountInfo } = useContext(AccountContext);
    const router = useRouter();
    const [errorMessage, setErrorMessage] = useState("");

    type Inputs = {
        email: string,
        password: string,
    }
    const {
        register,
        handleSubmit,
        formState: { errors }
    } = useForm<Inputs>({
        defaultValues: {
            email: 'jurgen@gmail.com',
            password: 'StrongPa1!ssword'
        }
    });

    const onSubmit : SubmitHandler<Inputs> = async (data: Inputs) => {
        console.log(data);
        setErrorMessage("Loading");
        try {
            const result = await accountService.loginAsync(data.email, data.password);
            console.log(result);
            if (result.errors) {
                setErrorMessage(result.statusCode + " - " + result.errors[0]);
                return;
            }
            setErrorMessage("");

            setAccountInfo!({
                jwt: result.data!.jwt,
                refreshToken: result.data!.refreshToken,
            });
            router.push("/");
        } catch (err) {
            setErrorMessage("Login Failed - " + (err as Error).message);
        }
    };
    return (
        <>
            <div className="row">
                <div className="col-4"></div>
                <div className="col-4">

                    {errorMessage}

                    <form onSubmit={handleSubmit(onSubmit)}>
                        <h2>Login</h2>
                        <hr />

                        <div className="text-danger validation-summary-valid" role="alert" data-valmsg-summary="true">
                        </div>
                        <div className="form-floating mb-3">
                            <input
                                className="form-control"
                                aria-required="true"
                                placeholder="name@example.com"
                                autoComplete="username"
                                type="email"
                                id="Input_Email"
                                {...register("email", { required: true })}
                            />
                            <label className="form-label" htmlFor="Input_Email">Email</label>
                            {
                                errors.email &&
                                <span className="text-danger field-validation-valid" data-valmsg-for="Input.Email" data-valmsg-replace="true">Required!</span>
                            }
                        </div>
                        <div className="form-floating mb-3">
                            <input
                                className="form-control"
                                aria-required="true"
                                placeholder="password"
                                type="password"
                                id="Input_Password"
                                autoComplete="current-password"
                                {...register("password", { required: true })}
                            />
                            <label className="form-label" htmlFor="Input_Password">Password</label>
                            {
                                errors.password &&
                                <span className="text-danger field-validation-valid" data-valmsg-for="Input.Email" data-valmsg-replace="true">Required!</span>
                            }
                        </div>

                        <div>
                            <button id="login-submit" type="submit" className="w-100 btn btn-lg btn-primary">Log in</button>
                        </div>

                    </form>
                </div>
            </div>

        </>
    );
}

// Gym_fin/Frontend(Vue)/src/views/Login.vue
<script setup lang="ts">
import AccountService from '@/services/AccountService';
import { useAuthStore } from '@/stores/auth';
import { ref } from 'vue';
import {useRouter} from 'vue-router'

const router = useRouter();
const authStore = useAuthStore();

let loginName = ref('');
let loginPassword = ref('');

let loginIsOngoing = ref(false);
let errors = ref<string[]>([]);

const doLogin = async () => {
  loginIsOngoing.value = true;

  const res = await AccountService.loginAsync(loginName.value, loginPassword.value);

  if (res.data) {
    authStore.saveTokens(res.data.jwt, res.data.refreshToken);
    errors.value = [];
    await router.push('/');
  } else {
    errors.value = res.errors!;
  }

  loginIsOngoing.value = false;
}

</script>

<template>
  <h1>Log in</h1>
  <div class="row">
    <div class="col-md-6">
      <section>
        <form id="account" method="post">
          <hr />

          <div class="form-floating mb-3">
            <input v-model="loginName" class="form-control" autocomplete="username" aria-required="true"
                   placeholder="name@example.com" type="email" id="Input_Email" name="Input.Email" value="" />
            <label class="form-label" for="Input_Email">Email</label>
          </div>

          <div class="form-floating mb-3">
            <input v-model="loginPassword" class="form-control" autocomplete="current-password"
                   aria-required="true" placeholder="password" type="password" id="Input_Password"
                   name="Input.Password" />
            <label class="form-label" for="Input_Password">Password</label>
          </div>

          <div>
            <button @click.prevent="doLogin" id="login-submit" type="submit"
                    class="w-100 btn btn-lg btn-primary">{{ loginIsOngoing ? 'Wait...' : 'Do login' }}</button>
          </div>
        </form>
      </section>
    </div>

  </div>

</template>

<style scoped></style>
